FROM postgres:17.4-alpine

# Install build dependencies
RUN apk add --no-cache --virtual .build-deps \
    git \
    build-base \
    clang19 \
    llvm19-dev

# Install pgvector
RUN cd /tmp && \
    git clone --branch v0.7.4 https://github.com/pgvector/pgvector.git && \
    cd pgvector && \
    make && \
    make install && \
    cd / && \
    rm -rf /tmp/pgvector

# Clean up build dependencies
RUN apk del .build-deps
